"""Top 1000 most traded US stocks by daily volume."""

# Ranked by volume on last trading day, from NYSE/NASDAQ/AMEX/ARCA/BATS
# Generated from Alpaca market data

UNIVERSE = [
    "NVDA", "SPDN", "TZA", "TQQQ", "BITO", "NVD", "AAL", "SPY", "SOXL", "IBIT", "NOK", "BMNR", "AIFF", "SPYM", "MARA",
    "ONDS", "HYG", "INTC", "PLTD", "QQQ", "PLUG", "SQQQ", "USO", "DNN", "TSLA", "NIO", "TSLL", "UVIX", "SOFI", "BBD",
    "NU", "LQD", "IWM", "SOXS", "PATH", "F", "EEM", "XLF", "ETHA", "SLV", "SNAP", "BAC", "OPEN", "TLT", "XLE",
    "HIMS", "EWZ", "PLTR", "SCHX", "CSTE", "MU", "HBAN", "AAPL", "CIFR", "BBAI", "RIG", "GDX", "AMZN", "AVGO", "KOS",
    "IREN", "PFE", "PBR", "AUR", "HOOD", "BTG", "ALIT", "SCO", "RWM", "OWL", "XLU", "GOVT", "RIVN", "VALE", "IBRX",
    "ABEV", "SCHD", "NFLX", "SOUN", "VG", "GRAB", "T", "EFA", "AMD", "WULF", "ZSPC", "BYND", "MSFT", "RGTI", "WBD",
    "QID", "ORCL", "AMC", "VOO", "JBLU", "IVV", "ABTC", "USHY", "CONL", "GOOGL", "MSTR", "CLSK", "STLA", "KEY", "EWY",
    "ACHR", "FXI", "AG", "CCL", "JOBY", "EOSE", "LYG", "XOM", "CLF", "SCHG", "RKT", "VZ", "NVTS", "FCX", "IJH",
    "QBTS", "CDE", "KRE", "MSTZ", "QYLD", "EMB", "PINS", "BTE", "ITUB", "CMG", "SPXS", "CMCSA", "CAG", "RIOT", "HAL",
    "NCLH", "IOVA", "KVUE", "IGV", "GGB", "CSCO", "META", "IEMG", "PCG", "KHC", "VCIT", "SNDK", "DRIP", "APLD", "MOS",
    "SH", "SMCI", "S", "UWMC", "SPIB", "SGOV", "CRWV", "PSLV", "RCAT", "AGNC", "KWEB", "BKR", "BITX", "CPNG", "ADBE",
    "TSM", "XLB", "HL", "SLB", "PTEN", "GOOG", "UCO", "ET", "PSKY", "PR", "UBER", "DOW", "TNA", "OXY", "HIMX",
    "RKLB", "CCC", "BTBT", "XLI", "XLK", "CNH", "UPXI", "WFC", "NBIS", "IONQ", "WIT", "PAR", "GT", "WMT", "SMR",
    "XLV", "VEA", "AAOI", "NOW", "CRM", "LYFT", "CFLT", "RDW", "PTON", "VXX", "B", "RXRX", "BP", "NKE", "IEFA",
    "INDI", "TE", "HPE", "RF", "MRVL", "NGD", "PYPL", "GERN", "INDV", "ARKK", "XLP", "SCHF", "CVX", "RSP", "SID",
    "TTD", "VWO", "HPQ", "BULL", "PSQ", "INDA", "DAL", "SCHB", "POET", "UAMY", "KGC", "DOG", "IAU", "COIN", "PDBC",
    "AES", "SAN", "KO", "SVCO", "UNG", "DVN", "WTI", "CSX", "IEF", "ULCC", "CVE", "GLD", "LYB", "XLY", "U",
    "BSX", "XLC", "NVO", "RZLV", "KALA", "USAR", "C", "FUBO", "LWLG", "CRCL", "UAA", "DYNF", "DKNG", "BIL", "IQ",
    "HLN", "BW", "ZSL", "XPEV", "BX", "SCHW", "FFAI", "HIVE", "BOIL", "NTSK", "COP", "CTRA", "USB", "USFR", "AXTI",
    "COMP", "WOOF", "CIG", "SABR", "BCS", "KMI", "EQNR", "XP", "EXK", "NEM", "INFY", "ITOT", "XBI", "LUV", "AVTR",
    "FNDX", "IAG", "CORZ", "TSLQ", "KLC", "SPXU", "CNQ", "BMBL", "EWJ", "MPT", "ADT", "WEN", "ETHU", "MDLZ", "FITB",
    "UEC", "RBRK", "BKLN", "YMM", "CPB", "ERIC", "FSLY", "UUUU", "VICI", "FOXA", "NXE", "DIS", "KDP", "LUMN", "SBUX",
    "BMY", "GTM", "KLAR", "VTEB", "SPDW", "ARCC", "GENI", "VTWO", "SCHH", "JD", "AMDL", "JNK", "QUBT", "JPM", "FIG",
    "BORR", "VTRS", "TFC", "SOC", "BA", "LRCX", "BAX", "VLY", "EXC", "DT", "EQX", "ABT", "AMPX", "PONY", "RITM",
    "VT", "AGG", "BN", "HDB", "QS", "IP", "SILJ", "RUN", "NVDL", "ETH", "EQT", "LUNR", "HUN", "SPYG", "TIC",
    "SVIX", "ASTS", "QXO", "TOST", "JETS", "WDC", "ARKB", "MIR", "APO", "IR", "GPK", "IYR", "GAP", "PPL", "IOT",
    "VXUS", "NFE", "MDT", "XLRE", "BITU", "INVH", "CTSH", "KOLD", "SHOP", "PAAS", "SBSW", "QCOM", "TEVA", "VGLT", "CF",
    "BBWI", "GIS", "BE", "SPTL", "SMH", "STM", "IGIB", "VGIT", "GDXJ", "EWH", "VNET", "VFC", "SPYV", "ON", "NEE",
    "WU", "DIA", "CGC", "PL", "JAAA", "RBLX", "HST", "PG", "APA", "MO", "JEPQ", "KKR", "SPYI", "APH", "GM",
    "GBTC", "FSM", "SHY", "XYZ", "GPGI", "MRK", "PFF", "BND", "FBTC", "SHEL", "BTI", "GLXY", "EWT", "CX", "VRT",
    "RXT", "SO", "IJR", "MCHP", "DOC", "NAT", "SRLN", "VTR", "XLG", "M", "UPST", "LAC", "COTY", "XRT", "NVDY",
    "SHV", "GLW", "IBN", "CCJ", "PM", "MRNA", "CPRT", "UPRO", "TME", "UVXY", "CLM", "AEG", "QQQI", "TMF", "ASM",
    "FISV", "JNJ", "SOXX", "DELL", "BABA", "GME", "MUR", "PTIR", "VTI", "VCSH", "ARAY", "ASPI", "CNC", "BIZD", "BLND",
    "PANW", "TPG", "AI", "FAST", "BEN", "PD", "CDXS", "IDEF", "IYW", "CRH", "EFG", "JHX", "SW", "KR", "UMAC",
    "ACWX", "ALM", "MVIS", "CRBG", "MS", "UAL", "FETH", "GLDM", "SVM", "HMY", "BITB", "SM", "ACWI", "EFV", "VIXY",
    "CARR", "AGQ", "OBDC", "COF", "EMXC", "OKLO", "QLD", "ESPR", "HBM", "NLY", "TEAM", "DX", "SPLB", "GE", "ASHR",
    "O", "FRMI", "AA", "MUB", "SJNK", "ALK", "CL", "VCLT", "ABBV", "JPST", "IUSB", "EW", "FLY", "MDY", "PBI",
    "CRML", "FE", "SPHY", "NTR", "BCRX", "SDS", "MP", "ROIV", "ORC", "DOUG", "WY", "ETHE", "MTCH", "ANET", "CHYM",
    "ERAS", "ASAN", "AMAT", "PEGA", "CRGY", "BB", "SSL", "TGT", "BTDR", "TECK", "FRSH", "CSGP", "STNE", "XRAY", "BNO",
    "LCID", "FLG", "UMC", "IWR", "ARES", "DHT", "TU", "REI", "CTVA", "GFI", "FLO", "SPXL", "SERV", "DAWN", "JEPI",
    "WBS", "PACB", "KNX", "ASX", "SGOL", "NWL", "ONON", "ALLO", "MDLN", "OMC", "TGB", "TEM", "BTC", "BGC", "CRF",
    "MSOS", "LW", "SARO", "PHYS", "USAS", "ENVX", "PRGO", "SUNB", "GFS", "XOP", "ORLY", "PSEC", "WMB", "FHN", "OSCR",
    "FNB", "V", "RTX", "FNGU", "BAM", "CZR", "IGSB", "CERS", "IVW", "UNH", "PDD", "GEVO", "DUK", "FIGR", "AMTX",
    "AQN", "PEP", "ZETA", "SLM", "GTLB", "GSK", "PAA", "AMCR", "CFG", "AEO", "URA", "FRO", "BHP", "SNCY", "IBG",
    "SANA", "USFD", "EBAY", "CHWY", "MFG", "CVS", "PURR", "SPMD", "DXD", "XEL", "CRDO", "LEN", "GEHC", "AFRM", "TSCO",
    "DBA", "KSS", "ARWR", "NOV", "CLOV", "FWONK", "VOD", "VTV", "YEXT", "UPS", "GEN", "DLTR", "BRKR", "TROX", "HLX",
    "ACI", "SBET", "BROS", "UDOW", "EWA", "LABD", "ADM", "EWC", "GILD", "BLDP", "IWF", "ASST", "IBM", "QQQM", "SCHV",
    "D", "LI", "SPSB", "EL", "CERT", "DGRO", "MCHI", "PCT", "WDAY", "TLYS", "TERN", "CPRI", "COPX", "VEU", "LTH",
    "EMLC", "UUP", "ACN", "GLL", "TNGX", "PAYO", "HOLX", "ATAI", "SONY", "MAGS", "GBDC", "AL", "CWAN", "CC", "EOG",
    "DHR", "JCI", "DJT", "GPRK", "CLVT", "BINC", "AU", "FANG", "TAL", "VLO", "HAFN", "MUFG", "FSK", "DXCM", "SGMO",
    "ENPH", "VNQ", "TBLL", "HTZ", "LYV", "DCH", "TDOC", "EVLV", "PAGS", "MMM", "SIVR", "MNST", "DDOG", "SSO", "AXIA",
    "EVGO", "FTNT", "GRNY", "COHR", "CELH", "SNOW", "TMC", "BNDX", "ADPT", "AR", "SUZ", "SU", "RYN", "SLNO", "IVZ",
    "SG", "LITE", "XENE", "LRMR", "CGDV", "UROY", "MNKD", "MGM", "TWO", "AMRZ", "OEF", "SHC", "APP", "REXR", "ZTS",
    "VISN", "DG", "OVV", "AKBA", "ENB", "RIO", "ALLY", "NRGV", "OCUL", "WRD", "NUVB", "AS", "ESI", "FIS", "RELY",
    "TXN", "PYLD", "VST", "EU", "CGGR", "KMB", "ICLN", "AEP", "IGLB", "SCHA", "NG", "PSX", "TRIP", "ETN", "FENY",
    "SCHI", "GO", "EMR", "EC", "LBRT", "FOX", "AMH", "SPLV", "ANGL", "QSR", "VIAV", "IWD", "NI", "USIG", "ALAB",
    "IHI", "NWG", "ARMK", "ARR", "OKE", "AKAM", "DOCU", "CNP", "IAUM", "STWD", "ALDX", "FLNC", "HOG", "IBKR", "STUB",
    "VGK", "NDAQ", "SPAB", "BEKE", "PBF", "PENN", "USDU", "SCHP", "SSRM", "BBY", "DB", "TRU", "COLD", "KIM", "NWSA",
    "HYMC", "TSN", "TTAN", "RZLT", "NVST", "TNYA", "ILF", "SN", "CART", "LAES", "HRL", "GNW", "BKD", "BCE", "ECX",
    "MET", "CG", "AMT", "CVNA", "BXSL", "TECS", "AGI", "SPSM", "BZ", "DNOW", "GLDD", "SCHE", "SLNH", "ATEC", "JEF",
    "LDI", "RRC", "SATS", "FPS", "SCHO", "PDI", "CE", "APG", "SIRI", "ADP", "RDY", "TJX", "ALT", "HON", "BFLY",
    "TPH", "ENTG", "ONB", "TBIL", "DAR", "OI", "INVZ", "FMC", "COLB", "ODFL", "OTIS", "AHR", "GPRO", "SVXY", "IEI",
    "RDDT", "GPN", "JBS", "FTI", "VYX", "STKL", "PGY", "PGX", "W", "NB", "SIL", "TMO", "BSV", "ELF", "DOCN",
    "HTGC", "HIG", "ABNB", "MKC", "QURE", "VONG", "REAL", "PUMP", "BK", "SE", "BIDU", "Z", "PRMB", "SGML", "ELAN",
    "ROKU", "AMKR", "SBRA", "INTR", "HSBC", "PNC", "KMX", "APEI", "ARKG", "BVN", "ECVT", "SPEM", "STX", "PAYX", "VSNT",
    "GLPI", "MQ", "MBLY", "BLMN", "UGP", "PZA", "ALKS", "AMPY", "IYZ", "AMRX", "XRX", "DHI", "UL", "NXPI", "AEM",
    "ADMA", "CTMX", "SRAD", "NVAX", "INDO", "UDR", "ESGE", "OLN", "WEAV", "TTEK",
]
